-- MySQL Script generated by MySQL Workbench
-- Tue Apr 10 18:58:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pzyko
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pzyko
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pzyko` DEFAULT CHARACTER SET utf8 ;
USE `pzyko` ;

-- -----------------------------------------------------
-- Table `pzyko`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzyko`.`user` (
  `uuid` CHAR(36) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `last_seen` BIGINT NOT NULL DEFAULT -1,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pzyko`.`claim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzyko`.`claim` (
  `id` INT NOT NULL,
  `world` VARCHAR(45) NOT NULL,
  `min_x` INT NOT NULL,
  `min_z` INT NOT NULL,
  `max_x` INT NOT NULL,
  `max_z` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzyko`.`claim_role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzyko`.`claim_role_permission` (
  `rolename` ENUM('ACCESS', 'CONTAINER', 'BUILD', 'MANAGE') NOT NULL,
  `permission` VARCHAR(45) NOT NULL,
  `value` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`rolename`, `permission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pzyko`.`claim_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzyko`.`claim_user_role` (
  `claim_id` INT NOT NULL,
  `user_uuid` CHAR(36) NOT NULL,
  `rolepermission` ENUM('ACCESS', 'CONTAINER', 'BUILD', 'MANAGE') NOT NULL,
  PRIMARY KEY (`claim_id`, `user_uuid`, `rolepermission`),
  INDEX `fk_claim_has_user_user1_idx` (`user_uuid` ASC),
  INDEX `fk_claim_has_user_claim_idx` (`claim_id` ASC),
  INDEX `fk_role_rolepermission1_idx` (`rolepermission` ASC),
  CONSTRAINT `fk_claim_has_user_claim`
    FOREIGN KEY (`claim_id`)
    REFERENCES `pzyko`.`claim` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_claim_has_user_user1`
    FOREIGN KEY (`user_uuid`)
    REFERENCES `pzyko`.`user` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_rolepermission1`
    FOREIGN KEY (`rolepermission`)
    REFERENCES `pzyko`.`claim_role_permission` (`rolename`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzyko`.`claim_flag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzyko`.`claim_flag` (
  `claim_id` INT NOT NULL,
  `flag` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`claim_id`, `flag`),
  INDEX `fk_claim_flag_claim1_idx` (`claim_id` ASC),
  CONSTRAINT `fk_claim_flag_claim1`
    FOREIGN KEY (`claim_id`)
    REFERENCES `pzyko`.`claim` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
