name: PzykoCore
version: 0.0.1
description: Core plugin for Pzyko.Org
author: Sagen
main: org.pzyko.pzykocore.PzykoCore
softdepend: [WorldEdit]
commands:
  pzyko:
    description: Information about this plugin
  claim:
    description: Commands for managing claims
